# syntax=docker/dockerfile:1.7

FROM node:22.5.1-alpine
WORKDIR /app
RUN npm install -g corepack@latest \
  && corepack enable \
  && corepack prepare pnpm@10.22.0 --activate

ENV NODE_ENV=development

COPY package.json pnpm-lock.yaml ./
RUN pnpm install

COPY prisma ./prisma
RUN pnpm prisma:generate

EXPOSE 3009

CMD ["pnpm", "run", "dev"]

